CREATE TABLE [dbo].[CAMPAIGN_BACKGROUND]
(
	[cmpb_cmpid] INT NOT NULL , 
    [cmpb_bid] INT NOT NULL, 
    PRIMARY KEY ([cmpb_bid], [cmpb_cmpid]), 
    CONSTRAINT [FK_CAMPAIGN_BACKGROUND_ToCAMPAIGN] FOREIGN KEY ([cmpb_cmpid]) REFERENCES [CAMPAIGN]([cmp_id]), 
    CONSTRAINT [FK_CAMPAIGN_BACKGROUND_ToBACKGROUND] FOREIGN KEY ([cmpb_bid]) REFERENCES [BACKGROUND]([b_id])
)
