CREATE TABLE [dbo].[CHARACTER_BACKGROUND]
(
	[cb_cid] INT NOT NULL , 
    [cb_bid] INT NOT NULL, 
    PRIMARY KEY ([cb_bid], [cb_cid]), 
    CONSTRAINT [FK_CHARACTER_BACKGROUND_ToCHARACTER] FOREIGN KEY ([cb_cid]) REFERENCES [CHARACTER]([c_id]), 
    CONSTRAINT [FK_CHARACTER_BACKGROUND_ToBACKGROUND] FOREIGN KEY ([cb_bid]) REFERENCES [BACKGROUND](b_id)
)
