CREATE TABLE [dbo].[CHARACTER_FEATS] (
    [cf_cid] INT NOT NULL,
    [cf_fid] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([cf_fid] ASC, [cf_cid] ASC),
    CONSTRAINT [FK_CHARACTER_FEATS_ToCHARACTER] FOREIGN KEY ([cf_cid]) REFERENCES [dbo].[CHARACTER] ([c_id]),
    CONSTRAINT [FK_CHARACTER_FEATS_ToFEATS] FOREIGN KEY ([cf_fid]) REFERENCES [dbo].[FEATS] ([f_id])
);

