CREATE TABLE [dbo].[CHARACTER_SPELLBOOK] (
    [cs_cid] INT NOT NULL,
    [cs_sid] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([cs_cid] ASC, [cs_sid] ASC),
    CONSTRAINT [FK_CHARACTER_SPELLBOOK_ToCHARACER] FOREIGN KEY ([cs_cid]) REFERENCES [dbo].[CHARACTER] ([c_id]),
    CONSTRAINT [FK_CHARACTER_SPELLBOOK_ToSPELLS] FOREIGN KEY ([cs_sid]) REFERENCES [dbo].[SPELLS] ([s_id])
);

