CREATE TABLE [dbo].[EVENT_OCCURRED_TYPES]
(
	[eot_eoid] INT NOT NULL , 
    [eot_etid] INT NOT NULL, 
    PRIMARY KEY ([eot_etid], [eot_eoid]), 
    CONSTRAINT [FK_EVENT_OCCURRED_TYPES_ToEVENT_OCCURRED] FOREIGN KEY ([eot_eoid]) REFERENCES [EVENT_OCCURRED]([eo_id]), 
    CONSTRAINT [FK_EVENT_OCCURRED_TYPES_ToEVENT_TYPE] FOREIGN KEY ([eot_etid]) REFERENCES [EVENT_TYPE]([et_id])
)
