CREATE TABLE [dbo].[ITEM_BACKGROUND]
(
	[ib_iid] INT NOT NULL , 
    [ib_bid] INT NOT NULL, 
    PRIMARY KEY ([ib_bid], [ib_iid]), 
    CONSTRAINT [FK_ITEM_BACKGROUND_ToITEM] FOREIGN KEY ([ib_iid]) REFERENCES [ITEM]([i_id]), 
    CONSTRAINT [FK_ITEM_BACKGROUND_ToBACKGROUND] FOREIGN KEY ([ib_bid]) REFERENCES [BACKGROUND]([b_id])
)
