CREATE TABLE [dbo].[QUESTLINE_BACKGROUND]
(
	[qlb_qlid] INT NOT NULL , 
    [qlb_bid] INT NOT NULL, 
    PRIMARY KEY ([qlb_bid], [qlb_qlid]), 
    CONSTRAINT [FK_QUESTLINE_BACKGROUND_ToQUESTLINE] FOREIGN KEY ([qlb_qlid]) REFERENCES [QUESTLINE]([ql_id]), 
    CONSTRAINT [FK_QUESTLINE_BACKGROUND_ToBACKGROUND] FOREIGN KEY ([qlb_bid]) REFERENCES [BACKGROUND]([b_id])
)
