CREATE TABLE [dbo].[QUEST_BACKGROUND]
(
	[qb_qid] INT NOT NULL , 
    [qb_bid] INT NOT NULL, 
    PRIMARY KEY ([qb_bid], [qb_qid]), 
    CONSTRAINT [FK_QUEST_BACKGROUND_ToQUEST] FOREIGN KEY ([qb_qid]) REFERENCES [QUEST]([q_id]), 
    CONSTRAINT [FK_QUEST_BACKGROUND_ToBACKGROUND] FOREIGN KEY ([qb_bid]) REFERENCES [BACKGROUND]([b_id])
)
